chore: Set Kotlin api version to 1.3
See:
Function references give runtime NoSuchMethodError when switching to 1.4
https://youtrack.jetbrains.com/issue/KT-39389